CREATE TABLE BOOK
(
    ID              INTEGER PRIMARY KEY AUTOINCREMENT,
    ISBN            BIGINT      NOT NULL UNIQUE,
    WRITER          VARCHAR(255) NOT NULL,
    TITLE           VARCHAR(255) NOT NULL,
    PUBLISHING_DATE DATE         NOT NULL
);


CREATE TABLE REVIEW
(
    ID            INTEGER PRIMARY KEY AUTOINCREMENT,
    BOOK_ISBN     BIGINT      NOT NULL,
    REVIEW_DATE   DATE         NOT NULL,
    REVIEW_TEXT   VARCHAR(255),
    REVIEW_RATING INTEGER      NOT NULL CHECK (REVIEW_RATING BETWEEN 1 AND 5),

    FOREIGN KEY (BOOK_ISBN) REFERENCES BOOK (ISBN) ON DELETE CASCADE
);